[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adit-service"
version = "0.1.0"

[project.scripts]
adit-service = "adit_service.app:main"